# 节点配置
node:
  # 节点ID，用于唯一标识该节点
  id: 101
  # 主节点URL
  master_url: http://10.0.0.5:8089
  master_heartbeat_url: /aihuman/cluster/heartbeat/
  master_task_url: /aihuman/task/anonymous/
#  #dev-config
#  master_url: http://localhost:1030
#  master_heartbeat_url: /dev-api/aihuman/cluster/heartbeat/
#  master_task_url: /dev-api/aihuman/task/anonymous/

# 调度配置
scheduler:
  # 心跳间隔（秒）
  heartbeat_interval: 5
  # 任务获取间隔（秒）
  task_fetch_interval: 5

# 日志配置
logger:
  # 日志文件路径
  file_path: ../logs/cluster_agent.log
  # 日志级别: TRACE, DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  # 日志格式
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"
  # 日志文件轮转
  rotation: "1 day"
  # 保留时间
  retention: "7 days"

# musetalk配置
musetalk:
  # musetalk的根目录
  base_dir: /root/zzz/MuseTalk
  env_bin:  /root/miniconda3/envs/musetalk/bin/python
#  # dev-config
#  base_dir: /opt/musetalk
#  bin: /Users/qiukai/Documents/Project/PycharmProject/ClusterAgent/agent/test.py
#  # 填写python3的路径
#  python_bin: /usr/bin/python3